name: 'plugin-check-precio-transferencia-bancaria'
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1